### ISSUE TITLE
ifではなくてリストなどで

### ISSUE THREAD

**Issue by SugaharaRintaro** [c0b21073/ProjExD#6]
https://github.com/c0b21073/ProjExD/blob/0cca7a13c9a12549f9dac028e680bc7ab67deaf3/ex03/maze.py#L49
 
画像のパスをリストに入れて
bird = list[bird_n]
can.create_image(cx, cy, image=bird, tag="bird")
で2行で書けると思う

**Comment by c0b21073** [comment]
ありがとうございます！
