### ISSUE TITLE
ゴールの色の変え方

### ISSUE THREAD

**Issue by c0b21047** [c0b21073/ProjExD#8]
https://github.com/c0b21073/ProjExD/blob/0cca7a13c9a12549f9dac028e680bc7ab67deaf3/ex03/maze.py#L100
まずmaze_sigが迷路の二次元リストであるため、そこのゴールの位置の値を変える(2がおすすめ)。次にmaze_maker.pyの28行目のリストにゴールの色を追加する。するとあら不思議になるはず

**Comment by c0b21073** [comment]
修正できなかったです。すみません。
